# Inserts a blank line between shell prompts
add_newline = true

format = """
$jobs\
$battery\
$time\
$status\
$os\
$container\
$shell\
$username\
$hostname\
$localip\
$shlvl\
$singularity\
$kubernetes\
$directory\
$vcsh\
$fossil_branch\
$fossil_metrics\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$pijul_channel\
$docker_context\
$nix_shell\
$conda\
$meson\
$spack\
$memory_usage\
$nats\
$direnv\
$env_var\
$crystal\
$custom\
$sudo\
$cmd_duration\
$line_break\
$character"""

[battery]
full_symbol = "• "
charging_symbol = "⇡ "
discharging_symbol = "⇣ "
unknown_symbol = "❓ "
empty_symbol = "❗ "

[erlang]
symbol = "ⓔ "

[nodejs]
symbol = "[⬢](bold green) "

[pulumi]
symbol = "🧊 "

[time]
disabled = false
format = '[\[$time\]]($style) '
style = 'green bold'

[typst]
symbol = "t "
